# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ac33103d99444dc54d2f645ac4418134281457866f59ae57bcb59c73f6403747843b014584cd79b9cacf2c02237019e1f5049010bbb5c403b57f0020e0f2c88

test:
  secret_key_base: 6795394b3df23bad778443df05450a1f70990e5e5c0a971983c59d9ec2e5ebdbec4a846bb66def1482786e764036b132b94a9fe533d12ed2f41f8dae535d3cc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
